// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutUsDocumentDataSlicesSlice =
  | TextOnlySlice
  | ServicesOverviewSlice
  | BoardSlice
  | ServiceOverviewSlice;

/**
 * Content for Um okkur documents
 */
interface AboutUsDocumentData {
  /**
   * Title field in *Um okkur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Um okkur*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * image 1 field in *Um okkur*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.image_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * image 2 field in *Um okkur*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.image_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *Um okkur*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.image_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Um okkur*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutUsDocumentDataSlicesSlice> /**
   * Meta Title field in *Um okkur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Um okkur*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Um okkur*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Um okkur document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutUsDocumentData>,
    "about_us",
    Lang
  >;

type AllNewsDocumentDataSlicesSlice = never;

/**
 * Content for Allar fréttir documents
 */
interface AllNewsDocumentData {
  /**
   * Title field in *Allar fréttir*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: all_news.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub title field in *Allar fréttir*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: all_news.sub_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Allar fréttir*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: all_news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AllNewsDocumentDataSlicesSlice> /**
   * Meta Title field in *Allar fréttir*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: all_news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Allar fréttir*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: all_news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Allar fréttir*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: all_news.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Allar fréttir document from Prismic
 *
 * - **API ID**: `all_news`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AllNewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AllNewsDocumentData>,
    "all_news",
    Lang
  >;

/**
 * Item in *Footer → Link group 1*
 */
export interface FooterDocumentDataLinkGroup1Item {
  /**
   * Link name field in *Footer → Link group 1*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.link_group_1[].link_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_name: prismic.KeyTextField;

  /**
   * Link field in *Footer → Link group 1*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.link_group_1[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Address field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * SSD number field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.ssd_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ssd_number: prismic.KeyTextField;

  /**
   * Link group 1 title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.link_group_1_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_1_title: prismic.KeyTextField;

  /**
   * Link group 1 field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.link_group_1[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  link_group_1: prismic.GroupField<Simplify<FooterDocumentDataLinkGroup1Item>>;

  /**
   * Email field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone number field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Facebook hlekkur field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.facebook_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  facebook_link: prismic.KeyTextField;

  /**
   * Opening hours 2 field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.opening_hours_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  opening_hours_2: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Forsíða → Benefits*
 */
export interface FrontPageDocumentDataBenefitsItem {
  /**
   * Title field in *Forsíða → Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.benefits[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Forsíða → Benefits*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.benefits[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Link field in *Forsíða → Benefits*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.benefits[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type FrontPageDocumentDataSlicesSlice =
  | WhyUsOverviewSlice
  | OrlofshusUmAlltLandSlice
  | AboutUsOverviewSlice;

/**
 * Content for Forsíða documents
 */
interface FrontPageDocumentData {
  /**
   * main title 1 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.main_title_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_title_1: prismic.KeyTextField;

  /**
   * Main title 2 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.main_title_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_title_2: prismic.KeyTextField;

  /**
   * Hero title 1 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_title_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title_1: prismic.KeyTextField;

  /**
   * Hero image field in *Forsíða*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Hero paragraph 1 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_paragraph_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_paragraph_1: prismic.KeyTextField;

  /**
   * Hero link text 1 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_link_text_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_link_text_1: prismic.KeyTextField;

  /**
   * Hero link 1 field in *Forsíða*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_link_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_link_1: prismic.LinkField;

  /**
   * Hero image 2 field in *Forsíða*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_image_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image_2: prismic.ImageField<never>;

  /**
   * Hero title 2 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_title_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title_2: prismic.KeyTextField;

  /**
   * Hero paragraph 2 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_paragraph_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_paragraph_2: prismic.KeyTextField;

  /**
   * Hero link text 2 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_link_text_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_link_text_2: prismic.KeyTextField;

  /**
   * Hero link 2 field in *Forsíða*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_link_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_link_2: prismic.LinkField;

  /**
   * Hero image 3 field in *Forsíða*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_image_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image_3: prismic.ImageField<never>;

  /**
   * Hero title 3 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_title_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title_3: prismic.KeyTextField;

  /**
   * Hero paragraph 3 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_paragraph_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_paragraph_3: prismic.KeyTextField;

  /**
   * Hero link text 3 field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_link_text_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_link_text_3: prismic.KeyTextField;

  /**
   * Hero link 3 field in *Forsíða*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.hero_link_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_link_3: prismic.LinkField;

  /**
   * Members benefits sub title field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.members_benefits_sub_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  members_benefits_sub_title: prismic.KeyTextField;

  /**
   * Members benefits title field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.members_benefits_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  members_benefits_title: prismic.KeyTextField;

  /**
   * Members benefits paragraph field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.members_benefits_paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  members_benefits_paragraph: prismic.KeyTextField;

  /**
   * Benefits field in *Forsíða*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.benefits[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  benefits: prismic.GroupField<Simplify<FrontPageDocumentDataBenefitsItem>>;

  /**
   * Slice Zone field in *Forsíða*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FrontPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: front_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Forsíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: front_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Forsíða*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: front_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Forsíða document from Prismic
 *
 * - **API ID**: `front_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FrontPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FrontPageDocumentData>,
    "front_page",
    Lang
  >;

/**
 * Item in *Header → Link group 1*
 */
export interface HeaderDocumentDataLinkGroup1Item {
  /**
   * Link text field in *Header → Link group 1*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_1[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link field in *Header → Link group 1*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_1[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Header → Link group 2*
 */
export interface HeaderDocumentDataLinkGroup2Item {
  /**
   * Link text field in *Header → Link group 2*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_2[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link field in *Header → Link group 2*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_2[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Header → Link group 3*
 */
export interface HeaderDocumentDataLinkGroup3Item {
  /**
   * Link text field in *Header → Link group 3*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_3[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link field in *Header → Link group 3*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_3[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Header → Link group 4*
 */
export interface HeaderDocumentDataLinkGroup4Item {
  /**
   * Link text field in *Header → Link group 4*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_4[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link field in *Header → Link group 4*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_4[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Link group 1 name field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_1_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_1_name: prismic.KeyTextField;

  /**
   * Link group 1 title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_1_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_1_title: prismic.KeyTextField;

  /**
   * Link group 1 paragraph field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_1_paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_1_paragraph: prismic.KeyTextField;

  /**
   * Link group 1 image 1 field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_1_image_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  link_group_1_image_1: prismic.ImageField<never>;

  /**
   * Link group 1 image 2 field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_1_image_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  link_group_1_image_2: prismic.ImageField<never>;

  /**
   * Link group 1 field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_1[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  link_group_1: prismic.GroupField<Simplify<HeaderDocumentDataLinkGroup1Item>>;

  /**
   * Link group 2 name field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_2_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_2_name: prismic.KeyTextField;

  /**
   * Link group 2 title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_2_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_2_title: prismic.KeyTextField;

  /**
   * Link group 2 paragraph field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_2_paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_2_paragraph: prismic.KeyTextField;

  /**
   * Link group 2 image 1 field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_2_image_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  link_group_2_image_1: prismic.ImageField<never>;

  /**
   * Link group 2 image 2 field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_2_image_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  link_group_2_image_2: prismic.ImageField<never>;

  /**
   * Link group 2 field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  link_group_2: prismic.GroupField<Simplify<HeaderDocumentDataLinkGroup2Item>>;

  /**
   * Link group 3 name field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_3_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_3_name: prismic.KeyTextField;

  /**
   * Link group 3 title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_3_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_3_title: prismic.KeyTextField;

  /**
   * Link group 3 paragraph field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_3_paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_3_paragraph: prismic.KeyTextField;

  /**
   * Link group 3 image 1 field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_3_image_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  link_group_3_image_1: prismic.ImageField<never>;

  /**
   * Link group 3 image 2 field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_3_image_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  link_group_3_image_2: prismic.ImageField<never>;

  /**
   * Link group 3 field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_3[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  link_group_3: prismic.GroupField<Simplify<HeaderDocumentDataLinkGroup3Item>>;

  /**
   * Link group 4 name field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_4_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_4_name: prismic.KeyTextField;

  /**
   * Link group 4 title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_4_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_4_title: prismic.KeyTextField;

  /**
   * Link group 4 paragraph field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_4_paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_group_4_paragraph: prismic.KeyTextField;

  /**
   * Link group 4 image 1 field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_4_image_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  link_group_4_image_1: prismic.ImageField<never>;

  /**
   * Link group 4 image 2 field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_4_image_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  link_group_4_image_2: prismic.ImageField<never>;

  /**
   * Link group 4 field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_group_4[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  link_group_4: prismic.GroupField<Simplify<HeaderDocumentDataLinkGroup4Item>>;

  /**
   * Link 5 name field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_5_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_5_name: prismic.KeyTextField;

  /**
   * Link 5 field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_5: prismic.LinkField;

  /**
   * Link 6 name field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_6_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_6_name: prismic.KeyTextField;

  /**
   * Link 6 field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_6
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_6: prismic.LinkField;

  /**
   * Link 7 name field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_7_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_7_name: prismic.KeyTextField;

  /**
   * Link 7 field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.link_7
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_7: prismic.LinkField;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type NewsDocumentDataSlicesSlice = never;

/**
 * Content for Frétt documents
 */
interface NewsDocumentData {
  /**
   * Image field in *Frétt*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Frétt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Frétt*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Date field in *Frétt*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: news.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Slice Zone field in *Frétt*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsDocumentDataSlicesSlice> /**
   * Meta Title field in *Frétt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Frétt*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Frétt*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Frétt document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;

type OrlofshusDocumentDataSlicesSlice =
  | SummerHouseSlice
  | AllHousesSlice
  | TextOnlySlice;

/**
 * Content for Orlofshús yfirlit documents
 */
interface OrlofshusDocumentData {
  /**
   * Hero image field in *Orlofshús yfirlit*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Hero title field in *Orlofshús yfirlit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Orlofshús yfirlit*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<OrlofshusDocumentDataSlicesSlice> /**
   * Meta Title field in *Orlofshús yfirlit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: orlofshus.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Orlofshús yfirlit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: orlofshus.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Orlofshús yfirlit*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Orlofshús yfirlit document from Prismic
 *
 * - **API ID**: `orlofshus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OrlofshusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OrlofshusDocumentData>,
    "orlofshus",
    Lang
  >;

type UmOkkurTextasidaDocumentDataSlicesSlice = never;

/**
 * Content for Um okkur textasíða documents
 */
interface UmOkkurTextasidaDocumentData {
  /**
   * Title field in *Um okkur textasíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: um_okkur_textasida.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Um okkur textasíða*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: um_okkur_textasida.paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Slice Zone field in *Um okkur textasíða*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: um_okkur_textasida.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<UmOkkurTextasidaDocumentDataSlicesSlice> /**
   * Meta Title field in *Um okkur textasíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: um_okkur_textasida.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Um okkur textasíða*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: um_okkur_textasida.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Um okkur textasíða*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: um_okkur_textasida.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Um okkur textasíða document from Prismic
 *
 * - **API ID**: `um_okkur_textasida`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UmOkkurTextasidaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<UmOkkurTextasidaDocumentData>,
    "um_okkur_textasida",
    Lang
  >;

export type AllDocumentTypes =
  | AboutUsDocument
  | AllNewsDocument
  | FooterDocument
  | FrontPageDocument
  | HeaderDocument
  | NewsDocument
  | OrlofshusDocument
  | UmOkkurTextasidaDocument;

/**
 * Primary content in *AboutUsOverview → Default → Primary*
 */
export interface AboutUsOverviewSliceDefaultPrimary {
  /**
   * Title field in *AboutUsOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_overview.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub title field in *AboutUsOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_overview.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Paragraph 1 field in *AboutUsOverview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_overview.default.primary.paragraph_1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_1: prismic.RichTextField;

  /**
   * image 1 field in *AboutUsOverview → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_overview.default.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Paragraph 2 field in *AboutUsOverview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_overview.default.primary.paragraph_2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_2: prismic.RichTextField;

  /**
   * Image 2 field in *AboutUsOverview → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_overview.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Paragraph 3 field in *AboutUsOverview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_overview.default.primary.paragraph_3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph_3: prismic.RichTextField;

  /**
   * Link text field in *AboutUsOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_overview.default.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link field in *AboutUsOverview → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us_overview.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for AboutUsOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutUsOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutUsOverview*
 */
type AboutUsOverviewSliceVariation = AboutUsOverviewSliceDefault;

/**
 * AboutUsOverview Shared Slice
 *
 * - **API ID**: `about_us_overview`
 * - **Description**: AboutUsOverview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutUsOverviewSlice = prismic.SharedSlice<
  "about_us_overview",
  AboutUsOverviewSliceVariation
>;

/**
 * Item in *AllHouses → Default → Primary → House*
 */
export interface AllHousesSliceDefaultPrimaryHouseItem {
  /**
   * House image field in *AllHouses → Default → Primary → House*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: all_houses.default.primary.house[].house_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  house_image: prismic.ImageField<never>;

  /**
   * House address field in *AllHouses → Default → Primary → House*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: all_houses.default.primary.house[].house_address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  house_address: prismic.KeyTextField;

  /**
   * House link field in *AllHouses → Default → Primary → House*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: all_houses.default.primary.house[].house_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  house_link: prismic.LinkField;
}

/**
 * Primary content in *AllHouses → Default → Primary*
 */
export interface AllHousesSliceDefaultPrimary {
  /**
   * Title field in *AllHouses → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: all_houses.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * House field in *AllHouses → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: all_houses.default.primary.house[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  house: prismic.GroupField<Simplify<AllHousesSliceDefaultPrimaryHouseItem>>;
}

/**
 * Default variation for AllHouses Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllHousesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AllHousesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AllHouses*
 */
type AllHousesSliceVariation = AllHousesSliceDefault;

/**
 * AllHouses Shared Slice
 *
 * - **API ID**: `all_houses`
 * - **Description**: AllHouses
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllHousesSlice = prismic.SharedSlice<
  "all_houses",
  AllHousesSliceVariation
>;

/**
 * Item in *Board → Default → Primary → Board members*
 */
export interface BoardSliceDefaultPrimaryBoardMembersItem {
  /**
   * Member name field in *Board → Default → Primary → Board members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: board.default.primary.board_members[].member_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  member_name: prismic.KeyTextField;

  /**
   * Member job field in *Board → Default → Primary → Board members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: board.default.primary.board_members[].member_job
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  member_job: prismic.KeyTextField;

  /**
   * Email field in *Board → Default → Primary → Board members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: board.default.primary.board_members[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone number field in *Board → Default → Primary → Board members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: board.default.primary.board_members[].phone_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;
}

/**
 * Primary content in *Board → Default → Primary*
 */
export interface BoardSliceDefaultPrimary {
  /**
   * Title field in *Board → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: board.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Board members field in *Board → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: board.default.primary.board_members[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  board_members: prismic.GroupField<
    Simplify<BoardSliceDefaultPrimaryBoardMembersItem>
  >;
}

/**
 * Default variation for Board Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BoardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BoardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Board*
 */
type BoardSliceVariation = BoardSliceDefault;

/**
 * Board Shared Slice
 *
 * - **API ID**: `board`
 * - **Description**: Board
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BoardSlice = prismic.SharedSlice<"board", BoardSliceVariation>;

/**
 * Primary content in *OrlofshusUmAlltLand → Default → Primary*
 */
export interface OrlofshusUmAlltLandSliceDefaultPrimary {
  /**
   * Sub title field in *OrlofshusUmAlltLand → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus_um_allt_land.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Title field in *OrlofshusUmAlltLand → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus_um_allt_land.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *OrlofshusUmAlltLand → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus_um_allt_land.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Link field in *OrlofshusUmAlltLand → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus_um_allt_land.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link text field in *OrlofshusUmAlltLand → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus_um_allt_land.default.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * image field in *OrlofshusUmAlltLand → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus_um_allt_land.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image 2 field in *OrlofshusUmAlltLand → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus_um_allt_land.default.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *OrlofshusUmAlltLand → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: orlofshus_um_allt_land.default.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;
}

/**
 * Default variation for OrlofshusUmAlltLand Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OrlofshusUmAlltLandSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OrlofshusUmAlltLandSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OrlofshusUmAlltLand*
 */
type OrlofshusUmAlltLandSliceVariation = OrlofshusUmAlltLandSliceDefault;

/**
 * OrlofshusUmAlltLand Shared Slice
 *
 * - **API ID**: `orlofshus_um_allt_land`
 * - **Description**: OrlofshusUmAlltLand
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OrlofshusUmAlltLandSlice = prismic.SharedSlice<
  "orlofshus_um_allt_land",
  OrlofshusUmAlltLandSliceVariation
>;

/**
 * Item in *CardsWithLink → Default → Primary → items*
 */
export interface ServiceOverviewSliceDefaultPrimaryItemsItem {
  /**
   * title field in *CardsWithLink → Default → Primary → items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_overview.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * paragraph field in *CardsWithLink → Default → Primary → items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_overview.default.primary.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * link field in *CardsWithLink → Default → Primary → items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: service_overview.default.primary.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *CardsWithLink → Default → Primary*
 */
export interface ServiceOverviewSliceDefaultPrimary {
  /**
   * Title field in *CardsWithLink → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_overview.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub title field in *CardsWithLink → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_overview.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * items field in *CardsWithLink → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_overview.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<ServiceOverviewSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for CardsWithLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardsWithLink*
 */
type ServiceOverviewSliceVariation = ServiceOverviewSliceDefault;

/**
 * CardsWithLink Shared Slice
 *
 * - **API ID**: `service_overview`
 * - **Description**: ServiceOverview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceOverviewSlice = prismic.SharedSlice<
  "service_overview",
  ServiceOverviewSliceVariation
>;

/**
 * Item in *ServicesOverview → Default → Primary → Service*
 */
export interface ServicesOverviewSliceDefaultPrimaryServiceItem {
  /**
   * Title field in *ServicesOverview → Default → Primary → Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.default.primary.service[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *ServicesOverview → Default → Primary → Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.default.primary.service[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Primary content in *ServicesOverview → Default → Primary*
 */
export interface ServicesOverviewSliceDefaultPrimary {
  /**
   * Title field in *ServicesOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Service field in *ServicesOverview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_overview.default.primary.service[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  service: prismic.GroupField<
    Simplify<ServicesOverviewSliceDefaultPrimaryServiceItem>
  >;
}

/**
 * Default variation for ServicesOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesOverview*
 */
type ServicesOverviewSliceVariation = ServicesOverviewSliceDefault;

/**
 * ServicesOverview Shared Slice
 *
 * - **API ID**: `services_overview`
 * - **Description**: ServicesOverview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesOverviewSlice = prismic.SharedSlice<
  "services_overview",
  ServicesOverviewSliceVariation
>;

/**
 * Item in *SummerHouse → Default → Primary → Images*
 */
export interface SummerHouseSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *SummerHouse → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: summer_house.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *SummerHouse → Default → Primary*
 */
export interface SummerHouseSliceDefaultPrimary {
  /**
   * Title field in *SummerHouse → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: summer_house.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *SummerHouse → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: summer_house.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Link to house field in *SummerHouse → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: summer_house.default.primary.link_to_house
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_house: prismic.LinkField;

  /**
   * Link text field in *SummerHouse → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: summer_house.default.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Images field in *SummerHouse → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: summer_house.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<SummerHouseSliceDefaultPrimaryImagesItem>
  >;

  /**
   * Link to all houses field in *SummerHouse → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: summer_house.default.primary.link_to_all_houses
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_all_houses: prismic.LinkField;

  /**
   * Link to all houses text field in *SummerHouse → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: summer_house.default.primary.link_to_all_houses_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_to_all_houses_text: prismic.KeyTextField;
}

/**
 * Default variation for SummerHouse Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SummerHouseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SummerHouseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SummerHouse*
 */
type SummerHouseSliceVariation = SummerHouseSliceDefault;

/**
 * SummerHouse Shared Slice
 *
 * - **API ID**: `summer_house`
 * - **Description**: SummerHouse
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SummerHouseSlice = prismic.SharedSlice<
  "summer_house",
  SummerHouseSliceVariation
>;

/**
 * Primary content in *TextAndTitle → Default → Primary*
 */
export interface TextOnlySliceDefaultPrimary {
  /**
   * Title field in *TextAndTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_only.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *TextAndTitle → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_only.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for TextAndTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextOnlySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextOnlySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextAndTitle*
 */
type TextOnlySliceVariation = TextOnlySliceDefault;

/**
 * TextAndTitle Shared Slice
 *
 * - **API ID**: `text_only`
 * - **Description**: TextOnly
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextOnlySlice = prismic.SharedSlice<
  "text_only",
  TextOnlySliceVariation
>;

/**
 * Item in *WhyUsOverview → Default → Primary → title and text items*
 */
export interface WhyUsOverviewSliceDefaultPrimaryTitleAndTextItemsItem {
  /**
   * title field in *WhyUsOverview → Default → Primary → title and text items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_overview.default.primary.title_and_text_items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *WhyUsOverview → Default → Primary → title and text items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_overview.default.primary.title_and_text_items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Primary content in *WhyUsOverview → Default → Primary*
 */
export interface WhyUsOverviewSliceDefaultPrimary {
  /**
   * Title field in *WhyUsOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_overview.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub title field in *WhyUsOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_overview.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Paragraph field in *WhyUsOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_overview.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * title and text items field in *WhyUsOverview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_overview.default.primary.title_and_text_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  title_and_text_items: prismic.GroupField<
    Simplify<WhyUsOverviewSliceDefaultPrimaryTitleAndTextItemsItem>
  >;
}

/**
 * Default variation for WhyUsOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyUsOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyUsOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhyUsOverview*
 */
type WhyUsOverviewSliceVariation = WhyUsOverviewSliceDefault;

/**
 * WhyUsOverview Shared Slice
 *
 * - **API ID**: `why_us_overview`
 * - **Description**: WhyUsOverview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyUsOverviewSlice = prismic.SharedSlice<
  "why_us_overview",
  WhyUsOverviewSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataSlicesSlice,
      AllNewsDocument,
      AllNewsDocumentData,
      AllNewsDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLinkGroup1Item,
      FrontPageDocument,
      FrontPageDocumentData,
      FrontPageDocumentDataBenefitsItem,
      FrontPageDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataLinkGroup1Item,
      HeaderDocumentDataLinkGroup2Item,
      HeaderDocumentDataLinkGroup3Item,
      HeaderDocumentDataLinkGroup4Item,
      NewsDocument,
      NewsDocumentData,
      NewsDocumentDataSlicesSlice,
      OrlofshusDocument,
      OrlofshusDocumentData,
      OrlofshusDocumentDataSlicesSlice,
      UmOkkurTextasidaDocument,
      UmOkkurTextasidaDocumentData,
      UmOkkurTextasidaDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutUsOverviewSlice,
      AboutUsOverviewSliceDefaultPrimary,
      AboutUsOverviewSliceVariation,
      AboutUsOverviewSliceDefault,
      AllHousesSlice,
      AllHousesSliceDefaultPrimaryHouseItem,
      AllHousesSliceDefaultPrimary,
      AllHousesSliceVariation,
      AllHousesSliceDefault,
      BoardSlice,
      BoardSliceDefaultPrimaryBoardMembersItem,
      BoardSliceDefaultPrimary,
      BoardSliceVariation,
      BoardSliceDefault,
      OrlofshusUmAlltLandSlice,
      OrlofshusUmAlltLandSliceDefaultPrimary,
      OrlofshusUmAlltLandSliceVariation,
      OrlofshusUmAlltLandSliceDefault,
      ServiceOverviewSlice,
      ServiceOverviewSliceDefaultPrimaryItemsItem,
      ServiceOverviewSliceDefaultPrimary,
      ServiceOverviewSliceVariation,
      ServiceOverviewSliceDefault,
      ServicesOverviewSlice,
      ServicesOverviewSliceDefaultPrimaryServiceItem,
      ServicesOverviewSliceDefaultPrimary,
      ServicesOverviewSliceVariation,
      ServicesOverviewSliceDefault,
      SummerHouseSlice,
      SummerHouseSliceDefaultPrimaryImagesItem,
      SummerHouseSliceDefaultPrimary,
      SummerHouseSliceVariation,
      SummerHouseSliceDefault,
      TextOnlySlice,
      TextOnlySliceDefaultPrimary,
      TextOnlySliceVariation,
      TextOnlySliceDefault,
      WhyUsOverviewSlice,
      WhyUsOverviewSliceDefaultPrimaryTitleAndTextItemsItem,
      WhyUsOverviewSliceDefaultPrimary,
      WhyUsOverviewSliceVariation,
      WhyUsOverviewSliceDefault,
    };
  }
}
