// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_overview: dynamic(() => import("./AboutUsOverview")),
  all_houses: dynamic(() => import("./AllHouses")),
  board: dynamic(() => import("./Board")),
  house: dynamic(() => import("./House")),
  house_amenities: dynamic(() => import("./HouseAmenities")),
  member_quote: dynamic(() => import("./MemberQuote")),
  orlofshus_um_allt_land: dynamic(() => import("./OrlofshusUmAlltLand")),
  service_overview: dynamic(() => import("./ServiceOverview")),
  text_only: dynamic(() => import("./TextOnly")),
  why_us_overview: dynamic(() => import("./WhyUsOverview")),
};
