// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_overview: dynamic(() => import("./AboutUsOverview")),
  all_houses: dynamic(() => import("./AllHouses")),
  board: dynamic(() => import("./Board")),
  button: dynamic(() => import("./Button")),
  image: dynamic(() => import("./Image")),
  orlofshus_um_allt_land: dynamic(() => import("./OrlofshusUmAlltLand")),
  plain_text: dynamic(() => import("./PlainText")),
  service_overview: dynamic(() => import("./CardsWithLink")),
  services_overview: dynamic(() => import("./ServicesOverview")),
  summer_house: dynamic(() => import("./SummerHouse")),
  text_only: dynamic(() => import("./TextAndTitle")),
  why_us_overview: dynamic(() => import("./WhyUsOverview")),
};
